config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'application#index'

  get '/', to: 'application#index'
  get 'about', to: 'application#about'
  get 'features', to: 'application#features'

  get 'user/profile', to: 'authenticated#profile'

  scope 'user', module: 'authenticated' do
    resources :characters
  end

  scope module: 'application' do
    resources :character_classes, path: 'classes'
  end
end

app/controllers/application/character_classes_controller.rb
module Application
  class CharacterClassesController < ApplicationController
    def index
      @character_classes = CharacterClass.all
    end

    def show
      @character_class = CharacterClass.find(params[:id])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # This controller should only contain publicly available functions.

  #Static home page
  def index;
  end

  # Static about page
  def about; end

  # Static features page
  def features; end
end

app/helpers/application/character_classes_helper.rb
module Application
  module CharacterClassesHelper
    # TODO: delete if not used
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path, class_name, method: :get)
    class_name += current_page?(link_path) ? ' active' : ''

    content_tag(:li, class: class_name) do
      link_to link_text, link_path, method: method
    end
  end
end

app/views/application/character_classes/_character_class.erb
<tr><td><%= link_to character_class.name, character_class_path(character_class) %></td></tr>

app/views/application/character_classes/_class_feat.html.erb
<p> <%= class_feat.name %></p>

app/views/application/character_classes/index.html.erb
<h1>Listing all classes</h1>

<table>

<%= render @character_classes %>
</table>

app/views/application/character_classes/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @character_class.name %>
  <%= render partial: 'class_feat', collection: @character_class.class_feats %>
</p>

<%= link_to 'Back', character_classes_path %>