config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'application#index'

  get '/', to: 'application#index'
  get 'about', to: 'application#about'
  get 'features', to: 'application#features'

  get 'user/profile', to: 'authenticated#profile'

  scope 'user', module: 'authenticated' do
    resources :characters
  end

  scope module: 'application' do
    resources :character_classes, path: 'classes'
  end
end

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col s12 m6 l6 center">
        <h2>contact</h2>
        <p>
          mail: info@lifeofdice.be
        </p>
        <p>
          tel:03/333.333
        </p>
      </div>
      <div class="col s12 m6 l6 center">
        <h2>logo</h2>
        <img src="" alt="logo life of dice">
      </div>
    </div>
    <div class="footer-copyright">
      <div class="centreren">&COPY 2018 Copyright: <span class="vet">Life of Dice</span></div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="nav-extended">
  <div class="row remove_padding_bot">
    <div class="nav-wrapper">


      <ul >
        <li class= 'col s12 m2 l6 center'>
          <%= link_to image_tag("", alt: "logo", class: 'responsive-img center'), root_path %>
        </li>

        <%= nav_link 'Home', root_path, 'col s4 m2 l1 center' %>
        <%= nav_link 'About', about_path, 'col s4 m2 l1 center' %>
        <%= nav_link 'Features', features_path, ' col s4 m2 l1 center' %>
        <% if user_signed_in? -%>
            <%= nav_link 'Profile'.html_safe, user_profile_path, 'col s6  m2 l1 center' %>
            <%= nav_link 'Logout', destroy_session_path(current_user), 'col s6  m2 l1 center', method: :delete %>
        <% else -%>
            <%= nav_link 'Register', new_registration_path(User), 'col s6 m2 l1 center' %>
            <%= nav_link 'Login', new_session_path(User), 'col s6  m2 l1 center' %>
        <% end -%>
      </ul>
    </div>
  </div>
</nav>