config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'application#index'

  get '/', to: 'application#index'
  get 'about', to: 'application#about'
  get 'features', to: 'application#features'

  get 'user/profile', to: 'authenticated#profile'

  scope 'user', module: 'authenticated' do
    resources :characters
  end

  scope module: 'application' do
    resources :character_classes, path: 'classes'
  end
end

app/models/character.rb
class Character
  include Mongoid::Document
  include Mongoid::Timestamps # We can track usage over time
  include Mongoid::Attributes::Dynamic # This will store which path is chosen for the class and race.
  include EffectNodes
  include Constants

  field :name, type: String

  # base stats (after the rolls, nothing else included)
  field :strength, type: Integer
  field :dexterity, type: Integer
  field :constitution, type: Integer
  field :intelligence, type: Integer
  field :wisdom, type: Integer
  field :charisma, type: Integer

  add_effect_node :strength
  add_effect_node :dexterity
  add_effect_node :constitution
  add_effect_node :intelligence
  add_effect_node :wisdom
  add_effect_node :charisma

  add_effect_node :weapon_proficiencies, type: :list, old: false
  add_effect_node :armor_proficiencies, type: :list, old: false
  add_effect_node :tool_proficiencies, type: :list, old: false

  def has_proficiency?(item)
    return false unless item
    case item.class
    when Items::Armor
      armor_proficiencies.include? item.armor_type.to_sym
    when Items::Weapon
      weapon_proficiencies.include? item.weapon_type.to_sym
    when Items::Tool
      tool_proficiencies.include? item.tool_type.to_sym
    else
      false
    end
  end

  def self.modifier(stat)
    ((stat - 10) / 2).floor
  end

  # read_only attr
  def character_lvl
    class_lvls.sum(:lvl)
  end

  def encumberred?
    inventory.carry_weight > 15 * strength
  end

  def attack_bonus
    attack_bonus = self.class.modifier(strength) # TODO: make dependable on weapon, finesse -> allow dex
    attack_bonus += proficiency_bonus if has_proficiency?(Inventory.equipped(inventory.weapons).first&.item)
    attack_bonus
  end
  add_effect_node :attack_bonus

  def equipped_armor
    Inventory.equipped(inventory.armors).first
  end
  def speed
    @speed ||= race.speed - equipped_armor.try(:item).try(:speed_penalty, self).to_i
  end
  add_effect_node :speed

  def proficiency_bonus
    PROFICIENCY_BONUS[character_lvl]
  end

  def ac
    if equipped_armor
      equipped_armor.item.calculated_ac(self)
    else
      10 + dexterity
    end
  end
  add_effect_node :ac

  def character_class_lvls
    RequestStore.store[:"class_lvls.#{id}"] ||= class_lvls.includes(:character_class)
  end

  embedded_in :user
  has_and_belongs_to_many :character_feats, inverse_of: nil, index: true
  embeds_many :class_lvls
  belongs_to :race, inverse_of: nil, index: true
  embeds_one :inventory
  embeds_one :hit_point

  accepts_nested_attributes_for :class_lvls, :inventory, :hit_point

  rails_admin do
    configure :character_feats do
      pretty_value do
        bindings[:object].send(:character_feats).map { |v| "#{v.name}: " + v.effects.collect(&:name).join(', ') }.join(' <br />').html_safe
      end
    end

    # TODO: find solution for this
    edit do
      exclude_fields :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma
    end
  end
end

app/controllers/authenticated/characters_controller.rb
module Authenticated
  class CharactersController < AuthenticatedController

    # GET /users/characters
    def index
      authorize Character
      # TODO: fix n+1 problem here, problem with embedded eager loading
      # @characters = current_user.characters.includes(:character_class, from: :class_lvls)
      @characters = current_user.characters
    end

    # GET /users/characters/:id
    def show
      @character = authorize current_user.characters.find(params[:id])
    end

    # POST /users/characters
    def create

    end

    # GET /users/characters/new
    def new
      authorize Character
    end

    # GET /users/characters/:id/edit
    def edit

    end

    # PATCH/PUT /users/characters/:id
    def update

    end

    # DELETE /users/characters/:id
    def destroy

    end
  end
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_action :authenticate_user!

  # This can be skipped with 'skip_authorization' if there is nothing to
  # authorize. In that case, you might consider not placing it here.
  after_action :verify_authorized

  def app

  end

  def profile
    skip_authorization
    ## just a function to populate your database during testing
    if user_signed_in?
      test_class = CharacterClass.create!(name: 'test_class', hit_dice: 8)
      multi_class = CharacterClass.create!(name: 'multi_class', hit_dice: 6)
      test_race = Race.create!(name: 'lol_race', speed: 25)
      char = Character.create!(name: 'tester', strength: 1, dexterity: 2, constitution: 3,
                               intelligence: 4, wisdom: 5, charisma: 6,
                               user: current_user, race: test_race)
      test = ClassLvl.create!(lvl: 2, character: char, character_class_id: test_class.id)
      testing = ClassLvl.create!(lvl: 9, character: char, character_class_id: multi_class.id)
    end
    race_feat = RacialFeat.create!(name: 'str bonus', race: current_user.characters.first.race,
                       description: 'this test race gains inteligence mod as bonus str at lvl 2', minimum_lvl: 2)
    Effect.create!(effect_node: 'strength', effect_function: '[0, self.class.modifier(intelligence)].max',
                   effectable: race_feat)
    Inventory.create!(character: char)
    HitPoint.create!(character: char)
  end
end

app/helpers/authenticated/characters_helper.rb
module Authenticated
  module CharactersHelper
    def class_lvl_string(class_lvl)
      class_lvl.character_class.name + ': ' + class_lvl.lvl.to_s
    end

    def class_lvl_strings(character)
      character.character_class_lvls.collect { |class_lvl| class_lvl_string class_lvl }
    end

    def classes_string(character)
      character.character_class_lvls.collect do |class_lvl|
        class_lvl.character_class.name
      end.join(' + ')
    end
  end
end

app/views/authenticated/characters/_character_li.html.erb
<%= link_to character_path(character), class: 'collection-item horizontal_centre' do %>
<div class=" character_li row remove_padding_bot">
  <div class="col s1"><%= character.character_lvl %></div>
  <div class="col s2"><%= character.name %></div>
  <div class="col s2"><%= character.race.name %></div>
  <div class="col s7"><%= classes_string(character) %></div>
</div>
<% end %>

app/views/authenticated/characters/_create_new.html.erb
<%= link_to new_character_path, class: 'horizontal_centre' do %>
<button type="button">Create New Character</button>
<% end %>

app/views/authenticated/characters/_hit_points.html.erb
<table>
  <tbody>
  <tr>
    <td>max_hp</td>
    <td><%= @character.hit_point.max_hp %></td>
    <td>current_hp</td>
    <td><%= @character.hit_point.current_hp%></td>
  </tr>
  </tbody>
</table>

app/views/authenticated/characters/index.html.erb
<!--<h1 class="center-align">Listing characters from <%#= (current_user.first_name + '&nbsp;'+ current_user.last_name).html_safe %></h1>-->
<h1 class="center-align">Listing characters from testing</h1>

<div id="table80">
  <%= render partial: 'create_new' %>
  <div class="collection with-header">
    <div class="row collection-header remove_padding_bot collection_title">
      <!-- TODO: hier moet nog race bij staan -->
      <div class="col s1">Lvl</div>
      <div class="col s2">Name</div>
      <div class="col s2">Race</div>
      <div class="col s7">Class</div>
    </div>

    <%= render partial: 'character_li', collection: @characters, as: :character %>
  </div>
</div>

app/views/authenticated/characters/new.html.erb
<h1>You are here to create a new character</h1>

app/views/authenticated/characters/show.html.erb
<strong>Name:</strong>
<p>
  <%= @character.name %>
</p>

<strong>Lvl / class:</strong>
<br>
<% class_lvl_strings(@character).each do |lvl_String| %>
  <p> <%= lvl_String %></p>
<% end %>
<%= render partial: 'hit_points' %>
<table>
  <tbody>
  <tr>
    <td>strength</td>
    <td><%= @character.strength %></td>
    <td><%= Character.modifier(@character.strength) %></td>
  </tr>
  <tr>
    <td>dexterity</td>
    <td><%= @character.dexterity %></td>
    <td><%= Character.modifier(@character.dexterity) %></td>
  </tr>
  <tr>
    <td>constitution</td>
    <td><%= @character.constitution %></td>
    <td><%= Character.modifier(@character.constitution) %></td>
  </tr>
  <tr>
    <td>intelligence</td>
    <td><%= @character.intelligence %></td>
    <td><%= Character.modifier(@character.intelligence) %></td>
  </tr>
  <tr>
    <td>wisdom</td>
    <td><%= @character.wisdom %></td>
    <td><%= Character.modifier(@character.wisdom) %></td>
  </tr>
  <tr>
    <td>charisma</td>
    <td><%= @character.charisma %></td>
    <td><%= Character.modifier(@character.charisma) %></td>
  </tr>
  <tr>
    <td>attack bonus</td>
    <td colspan="2"><%= @character.attack_bonus %></td>
  </tr>
  <tr>
    <td>ac</td>
    <td colspan="2"><%= @character.ac %></td>
  </tr>
  <tr>
    <td>speed</td>
    <td colspan="2"><%= @character.speed %></td>
  </tr>
  <tr>
    <td>can carry? (carried weight)</td>
    <td><%= ! @character.encumberred? %></td>
    <td><%= @character.inventory.carry_weight %></td>
  </tr>
  <tr>
    <td>money</td>
    <td><%= @character.inventory.platinum %></td>
    <td>platinum</td>
  </tr>
  <tr>
    <td></td>
    <td><%= @character.inventory.gold %></td>
    <td>gold</td>
  </tr>
  <tr>
    <td></td>
    <td><%= @character.inventory.electrum %></td>
    <td>electrum</td>
  </tr>
  <tr>
    <td></td>
    <td><%= @character.inventory.silver %></td>
    <td>silver</td>
  </tr>
  <tr>
    <td></td>
    <td><%= @character.inventory.copper %></td>
    <td>copper</td>
  </tr>
  </tbody>
</table>


<%= link_to 'Back', characters_path %>